version: "3"

# docker run --rm --name courses-database -v courses-data:/var/lib/postgresql/data -p 5434:5432
# -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=timelydb -d postgres:13-alpine
services:
  courses-database:
    image: "postgres:13-alpine"
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=12345678"
      - "POSTGRES_DB=timelydb"